{% set version = "1.4.1" %}

package:
  name: pyjnius-split
  version: {{ version }}

source:
  url: https://github.com/kivy/pyjnius/archive/{{ version }}.zip
  sha256: a57acc0d3163ddb894a1cffa1c484e31dffe376820e609107a571e525e4dd3d6
  patches:
    # this patch makes ant create one jar including the test classes;
    # it is only relevant for the output pyjnius-tests, as the normal
    # package doesn't need the java classes to work
    - patches/0001-put-test-classes-into-pyjnius.jar.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - openjdk {{ openjdk }}
    - python  {{ python }}
    - apache-ant
    - cython
    - make        # [linux]
    - setuptools
  host:
    - openjdk {{ openjdk }}
    - python  {{ python }}
    - pip         # [win]
    - cython      # [win]
    - wheel       # [win]
    - setuptools  # [win]

outputs:
  - name: pyjnius
    script: build-pkg.sh   # [not win]
    script: build-pkg.bat  # [win]
    requirements:
      host:
        - openjdk {{ openjdk }}
        - python  {{ python }}
        - pip
        - six
      run:
        - openjdk
        - python
        - six
        # unfortunately, pyjinius run-depends on setuptools, see
        # https://github.com/kivy/pyjnius/blob/1.4.1/jnius_config.py#L72
        - setuptools
    test:
      files:
        - test_pyjnius.py
      imports:
        - jnius
        - jnius.env
        - jnius_config
      commands:
        - python test_pyjnius.py

  - name: pyjnius-tests
    script: build-tests.sh   # [not win]
    script: build-tests.bat  # [win]
    requirements:
      run:
        - {{ pin_subpackage('pyjnius', exact=True) }}
    test:
      requires:
        - pytest
      source_files:
        - tests/
      commands:
        # need to extend CLASSPATH as there are some java-based tests
        - export CLASSPATH="$PREFIX/share/pyjnius/*:$CLASSPATH"  # [not win]
        - set "CLASSPATH=%PREFIX%\share\pyjnius\*;%CLASSPATH%"   # [win]
        - pytest -v tests/

about:
  home: https://github.com/kivy/pyjnius
  license: MIT
  license_file: LICENSE
  summary: A Python module to access Java classes as Python classes using JNI (shared memory)

extra:
  recipe-maintainers:
    - hanslovsky
    - hadim
    - KeyWeeUsr
    - ctrueden
    - h-vetinari
  feedstock-name: pyjnius
