{% set version = "1.7.0" %}

{% if openjdk is undefined %}
{% set openjdk = "*" %}
{% endif %}

package:
  name: pyjnius
  version: {{ version }}

source:
  url: https://github.com/kivy/pyjnius/archive/{{ version }}.zip
  sha256: 0a0655257ae0b11abb949665c0ed88eb6b5b0b25d9a78271c32f8f81ffb5d977

build:
  number: 0
  string: py{{ CONDA_PY }}jdk{{ openjdk|int or "latest" }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  {% if (openjdk|int or 99) == 11 %}
  # unclear but reproducible segfaults for the oldest possible combination on windows
  skip: true  # [win and py==310]
  {% endif %}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make                   # [unix]
    - sed                    # [unix]
  host:
    - openjdk
    - python
    - cython <3.1.0    # >=3.1.0 breaks, pyjnius requires upstream fix
    - pip
    - setuptools
    - ant
  run:
    - openjdk
    - python
test:
  imports:
    - jnius
    - jnius.env
    - jnius_config
  requires:
    - pytest
  files:
    - test_pyjnius.py
  source_files:
    # created in source directory by ant (cf. build.sh / bld.bat)
    - build/test-classes
    - tests/
  commands:
    - python test_pyjnius.py
    # adapt CLASSPATH to pick up test classes
    - export CLASSPATH="$CLASSPATH:./build/test-classes"  # [unix]
    - set "CLASSPATH=%CLASSPATH%;build/test-classes"      # [win]
    - pytest -v tests/

about:
  home: https://github.com/kivy/pyjnius
  license: MIT
  license_file: LICENSE
  summary: A Python module to access Java classes as Python classes using JNI (shared memory)

extra:
  recipe-maintainers:
    - KeyWeeUsr
    - h-vetinari
