{% set version = "1.6.1" %}

{% if openjdk is undefined %}
{% set openjdk = "*" %}
{% endif %}

package:
  name: pyjnius
  version: {{ version }}

source:
  url: https://github.com/kivy/pyjnius/archive/{{ version }}.zip
  sha256: 842df6799d2011cba761b28ce265541456d4a39c9d70786871ed8f66880606d3

build:
  number: 1
  string: py{{ CONDA_PY }}jdk{{ openjdk|int or "latest" }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make                   # [unix]
    - sed                    # [unix]
  host:
    - openjdk
    - python
    - cython
    - pip
    - setuptools
    - ant
  run:
    - openjdk
    - python
test:
  imports:
    - jnius
    - jnius.env
    - jnius_config
  requires:
    - pytest
  files:
    - test_pyjnius.py
  source_files:
    # created in source directory by ant (cf. build.sh / bld.bat)
    - build/test-classes
    - tests/
  commands:
    - python test_pyjnius.py
    # adapt CLASSPATH to pick up test classes
    - export CLASSPATH="$CLASSPATH:./build/test-classes"  # [unix]
    - set "CLASSPATH=%CLASSPATH%;build/test-classes"      # [win]
    {% set tests_to_skip = "_not_a_real_test" %}
    {% if (openjdk|int or 21) >= 21 %}
    # skip a test that doesn't work with newer jdk, see
    # https://github.com/kivy/pyjnius/issues/736
    {% set tests_to_skip = tests_to_skip + " or test_hierharchy_arraylist" %}
    {% endif %}
    - pytest -v tests/ -k "not ({{ tests_to_skip }})"

about:
  home: https://github.com/kivy/pyjnius
  license: MIT
  license_file: LICENSE
  summary: A Python module to access Java classes as Python classes using JNI (shared memory)

extra:
  recipe-maintainers:
    - KeyWeeUsr
    - h-vetinari
