{% set name = "pyjnius" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kivy/pyjnius/archive/{{ version }}.zip
  sha256: 3c9b1542779e076d8327eb9716350af7024cc5708b8bdb6b83492e267b074bea

build:
  number: 0
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - openjdk
    - python
    - cython
    - pip
    - six >=1.7.0
    - nose
    - ant
    - pytest
  run:
    - openjdk
    - python
    - six >=1.7.0
    - setuptools

about:
  home: https://github.com/kivy/pyjnius
  license: MIT
  license_file: LICENSE
  summary: A Python module to access Java classes as Python classes using JNI (shared memory)

extra:
  recipe-maintainers:
    - hanslovsky
    - KeyWeeUsr
