{% set name = "pyjnius" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kivy/pyjnius/archive/{{ version }}.zip
  sha256: 4bbae6fa9e3b7c22c2e9e76dbfe89ad3086f1992f64c420ccb259dfa1bec14ff

build:
  number: 0
  skip: true  # [py2k]

requirements:
 build:
   - {{ compiler('c') }}
   - {{ compiler('cxx') }}
 host:
   - openjdk
   - python
   - cython
   - pip
   - six >=1.7.0
   - nose
   - ant
 run:
   - openjdk
   - python
   - six >=1.7.0
   - setuptools

about:
  home: https://github.com/kivy/pyjnius
  license: MIT
  license_file: LICENSE
  summary: "A Python module to access Java classes as Python classes using JNI (shared memory)"

extra:
  recipe-maintainers:
     - hanslovsky
     - hadim
     - KeyWeeUsr
     - ctrueden
