{% set name = "pyjnius" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kivy/pyjnius/archive/{{ version }}.zip
  sha256: 4bd04faf7dc11b58c4e97f1994d5a7fc7a5aa1f959b3adf80e44634f0d8ecc82

build:
  number: 0
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - openjdk
    - python
    - cython
    - pip
    - six >=1.7.0
    - nose
    - ant
  run:
    - openjdk
    - python
    - six >=1.7.0
    - setuptools

about:
  home: https://github.com/kivy/pyjnius
  license: MIT
  license_file: LICENSE
  summary: A Python module to access Java classes as Python classes using JNI (shared memory)

extra:
  recipe-maintainers:
    - hanslovsky
    - hadim
    - KeyWeeUsr
