{% set name = "pyjnius" %}
{% set version = "1.1.3.dev0.b212d5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  #sha256: 0bc70b48eb764b20b017e44ef2df6eae94e4a2f90ae63160d2a166c406e1ccf9
  # Currently testing on pyjnius master
  url: https://github.com/kivy/pyjnius/archive/b212d57d894ee62d2f48c9d82d28a015e8d548b8.zip
  sha256: 189c060c46dacc052a5a573124224f4292f2cd41bbd6b86d9e05667d643975c9

build:
  number: 1001
  skip: true  # [py2k]

requirements:
 build:
   - {{ compiler('c') }}
   - {{ compiler('cxx') }}
 host:
   - openjdk
   - python
   - cython
   - pip
   - six >=1.7.0
   - nose
   - ant
 run:
   - openjdk
   - python
   - six >=1.7.0
   - setuptools

about:
  home: https://github.com/kivy/pyjnius
  license: MIT
  license_file: LICENSE
  summary: "A Python module to access Java classes as Python classes using JNI (shared memory)"

extra:
  recipe-maintainers:
     - hanslovsky
     - hadim
