{% set version = "1.4.1" %}

package:
  name: pyjnius
  version: {{ version }}

source:
  url: https://github.com/kivy/pyjnius/archive/{{ version }}.zip
  sha256: a57acc0d3163ddb894a1cffa1c484e31dffe376820e609107a571e525e4dd3d6

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - openjdk
    - python
    - cython
    - pip
    - six
    - nose
    - apache-ant
  run:
    - openjdk
    - python
    - six
    - setuptools
test:
  # will also execute run_test.py
  imports:
    - jnius
  requires:
    - pytest
  source_files:
    - tests/
  commands:
    # need to set CLASSPATH correctly as there are some java-based tests
    - export CLASSPATH="${PREFIX}/share/pyjnius/"  # [not win]
    - set "CLASSPATH=%PREFIX%/share/pyjnius/"      # [win]
    - ls ${CLASSPATH}  # [not win]
    - dir %CLASSPATH%  # [not win]
    - pytest -v tests/

about:
  home: https://github.com/kivy/pyjnius
  license: MIT
  license_file: LICENSE
  summary: A Python module to access Java classes as Python classes using JNI (shared memory)

extra:
  recipe-maintainers:
    - hanslovsky
    - hadim
    - KeyWeeUsr
    - ctrueden
    - h-vetinari
