travis:
  secure:
    BINSTAR_TOKEN: BiCJmPN9jdgBrppK8cWlAuiRkZ6Cqdh5RSDNUclAYezII/s8DN8H3bqUGSzLPS3C6H8lXYB1lOgA7YjKGOqQ1MDGOOUI9TWnDvaxhNZ9ATe4/vj2/rvSJCs2kJXKo5N/JynWXtHTaxHOtMVJVIepgGkemjTGn4AqdhrM2mUEdpZiC0h3Xy8IpK3O85IL8P8L612DRV8PfyFTzSbnnALJjTzNvbH0rCxWxn6Lq3sTRB21pkYp46ZbmGEaL0w9/AvlcAev6OnZ3+hzj2JRw+jh4mvGUON8mgm4kIapGHE+C61nQL/Z2RErVdwRFucLuIOX+XYVkNZCssrQyDQolx99MZuFf65xL3JxymtGMqJXsmhiBaoFHNy5YpVzxcMHbWV0etdYRyVCit2Z0Z26aUpfA0sXRRgkI5QZCOMBJFVzBJxqu00/FFvM9KxbLJ+itHfuYtU8fs2nlFi3Epd+kamY3Jkt/JGCkVaCl9WRb5Fj7DF1x5eHzNEBzbCLzUtayv8v6EyiKXc8f6ugHPFh3DRf/Stdz9W65XNaK59gBdHmPfvN1j0zlwBzrPRh1/dtXBhJ+fw4/X4iyVeSJy5jo7Q74DG+jdQLaWE/htZZLfkAWfXFxS4KBlVL9oP46q126umLMatCIz1lbqf+LyGvdP0lmGF0uT6ClE1FmypGqMmiK9c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
